### ISSUE TITLE
vlad cluster center for custom dataset

### ISSUE THREAD

**Issue by unnamed333user** [AnyLoc/AnyLoc#22]
Hi @TheProjectsGuy , thank you for such a great project.
I can run the anyloc_vlad_generate.py file. But now I wan to extract the feature with dinov2+vlad on my custom dataset. Iam struggling in creating the cluster center with Vlad. Can you guide me how to create cluster center ? 
Tks~

**Comment by TheProjectsGuy** [comment]
Hey there, sorry this issue slipped through. I'm assuming that you want to create cluster centers (what we call "VLAD vocabularies") and not really use the AnyLoc method (that comes with a set of cluster centers - each for a certain "Domain" fit for deployment).
You can use the following scripts
- For DINOv2: [dino_v2_global_vocab_vlad.py](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_v2_global_vocab_vlad.py) (see [dino_v2_global_vocab_vlad_ablations.sh](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_v2_global_vocab_vlad_ablations.sh) for arguments)
- For DINOv1: [dino_global_vocab_vlad.py](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_global_vocab_vlad.py) (see [dino_global_vocab_vlad_ablations.sh](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_global_vocab_vlad_ablations.sh) for arguments)

These would work for the datasets we have tested. However, since you mention that you have a custom dataset, you'll need to implement it in a separate class and put it here (see [custom_datasets](https://github.com/AnyLoc/AnyLoc/tree/main/custom_datasets) for example)

https://github.com/AnyLoc/AnyLoc/blob/2ae462dbce05a2741fe8d075a1313488804e29a3/scripts/dino_v2_global_vocab_vlad.py#L105-L116

I'd refer you to issue #8 for more information. Let me know if that helps.
